server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 /DenueAgs/;
  }

  location /DenueAgs/assets/ {
    try_files $uri =404;
    expires 7d;
    add_header Cache-Control "public, immutable";
  }

  location /DenueAgs/ {
    try_files $uri $uri/ /DenueAgs/index.html;
  }

  location / {
    return 404;
  }
}
